
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_componets/Navbar";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "./_providers/MySessionProvider";
import CardContextProvider from "./_context/CardContextProvider";
import { getMyUserCart } from "./_actions/card.action";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userCart = await getMyUserCart()
  return (
    <html
      lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>

        <MySessionProvider>

        <CardContextProvider userCart={userCart}>

        <Toaster />
        <Navbar/>
        {children}

        </CardContextProvider>
        
        </MySessionProvider>

        </body>
    </html>
  );
}
